apiVersion: v1
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://postgres:5432/argocd
    spring.datasource.username=argocd
kind: ConfigMap
metadata:
  name: spring-endpoints-configmap
  namespace: argcd


